### ISSUE TITLE
вылетает при запуске

### ISSUE THREAD

**Issue by pagapitov** [PavlikBender/ScreTran#5]
приветствую,вылетает и последняя и 1.2.6 сразу при запуске ,win 10

```
Имя сбойного приложения: ScreTran.exe, версия: 1.3.0.0, метка времени: 0x67110000
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.3758, метка времени: 0xd80f8f12
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002cf19
Идентификатор сбойного процесса: 0x15e0
Время запуска сбойного приложения: 0x01db55be75f7f637
Путь сбойного приложения: D:\ScreTran\ScreTran.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: d56e4a1d-ee95-4002-a340-74fa3cd098eb
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
```

Application: ScreTran.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Вызов конструктора для типа "ScreTran.MainWindow", удовлетворяющего указанным ограничениям привязки, привел к выдаче исключения.
 ---> System.DllNotFoundException: Unable to load shared library 'paddle_inference_c', dependencies load status:
libiomp5md.dll: OK, handle=7ff8865b0000
mklml.dll: OK, handle=7ff880d30000
onnxruntime.dll: OK, handle=7ff8805a0000
onnxruntime_providers_shared.dll: OK, handle=7ff8d4950000
paddle2onnx.dll: OK, handle=7ff8801e0000
openblas.dll: FAIL, handle=0
mkldnn.dll: OK, handle=7ff87db80000
 ---> System.DllNotFoundException: Unable to load DLL 'paddle_inference_c' or one of its dependencies: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL). (0x8007045A)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Sdcb.PaddleInference.Native.PaddleInferenceLibLoader.LoadPaddleDependencies(String libraryName, Assembly assembly, Nullable`1 searchPath, String[] knownDependencies)
   --- End of inner exception stack trace ---
   at Sdcb.PaddleInference.Native.PaddleInferenceLibLoader.LoadPaddleDependencies(String libraryName, Assembly assembly, Nullable`1 searchPath, String[] knownDependencies)
   at Sdcb.PaddleInference.Native.PaddleInferenceLibLoader.PaddleImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sdcb.PaddleInference.Native.PaddleNative.PD_ConfigCreate()
   at Sdcb.PaddleInference.PaddleConfig..ctor()
   at Sdcb.PaddleInference.PaddleConfig.FromMemoryModel(Byte[] programBuffer, Byte[] paramsBuffer)
   at Sdcb.PaddleOCR.Models.Local.Details.Utils.LocalModel(String key, ModelVersion version)
   at Sdcb.PaddleOCR.Models.Local.LocalDetectionModel.CreateConfig()
   at Sdcb.PaddleOCR.PaddleOcrDetector..ctor(DetectionModel model, Action`1 configure)
   at Sdcb.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, Action`1 device)
   at ScreTran.ExecutionService.InitializePaddleOcr() in C:\Users\bbben\source\repos\ScreTran\Services\ExecutionService.cs:line 114
   at ScreTran.ExecutionService..ctor(ISettingsService settingsService, IParametersService parametersService, ITranslationService translationService, IWindowService windowService) in C:\Users\bbben\source\repos\ScreTran\Services\ExecutionService.cs:line 40
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at ScreTran.App.GetService[T]() in C:\Users\bbben\source\repos\ScreTran\App.xaml.cs:line 47
   at ScreTran.MainWindow..ctor() in C:\Users\bbben\source\repos\ScreTran\MainWindow.xaml.cs:line 34
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScreTran.App.Main()

извиняюсь,хз как под спойлер убрать

**Comment by PavlikBender** [comment]
Привет, у меня win11 и приложение я писал под него. На win10 у меня нет возможности протестировать и сказать будет ли оно там запускаться и корректно работать. Для тебя выпустил билд, который по идее должен запуститься на win10 - проверь и отпишись пожалуйста - https://github.com/PavlikBender/ScreTran/releases/tag/v1.3.1a

**Comment by PavlikBender** [comment]
@pagapitov Кажется нашёл причину поставь https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by pagapitov** [comment]
ну пока без этого не пошло,так же вылетает,щас пробую на 11 и ту 1.3.0 и тестовую проверю+vc

**Comment by pagapitov** [comment]
@PavlikBender  ничего хорошего не вышло,на 11 у меня не запускается и на 10 тоже,пробовал переустановить dotnet-sdk-8.0.300-win-x64, VC_redist.x64, windowsdesktop-runtime-8.0.0-win-x64. не хочет

**Comment by PavlikBender** [comment]
@pagapitov хмм странно я в windows sandbox-е (а это эмулятор чистой win11) проверял - запускается работает. Сейчас запустил на ноуте с win11 22H3 тоже полёт нормальный

**Comment by pagapitov** [comment]
@PavlikBender  я запускал на win 11 23h3 тоже,ну у меня не поддерживаемое оборудование,хз,может у меня комп слаб

**Comment by PavlikBender** [comment]
@pagapitov а какой то текст ошибки в 11 винде есть?

**Comment by pagapitov** [comment]
@PavlikBender  он примерно тот же, appcrash KERNELBASE.dll и paddle_inference_c

**Comment by PavlikBender** [comment]
@pagapitov я использую библиотеку PaddleSharp и там как раз эта ошибка и возникает. Рекомендации по устранению я тебе уже скидывал - https://github.com/sdcb/PaddleSharp?tab=readme-ov-file#why-my-code-runs-good-in-my-windows-machine-but-dllnotfoundexception-in-other-machine-

**Comment by PavlikBender** [comment]
Как время освободиться попробую накатить 10ку в hyper-v и попытаюсь воспроизвести у себя.
@pagapitov подскажи какой у тебя проц?

**Comment by pagapitov** [comment]
@PavlikBender  там почитал в переводе,dll попробовал для вин7,не помогло,про использование видеокарты сложно выглядит,посмотрел свой процессор,avx не поддерживает, слишком старый,спасибо за помошь,не буду больше мучать комп,попробую может дома,там вроде посвежее процессор

**Comment by pagapitov** [comment]
@PavlikBender  я уже пропробовал,не хочет в песочнице так же
проц amd x2 245

**Comment by pagapitov** [comment]
@PavlikBender я отпишусь если заработает,дома тоже 10

**Comment by PavlikBender** [comment]
@pagapitov про GPU это с моей стороны ещё надо библиотеку подключать, а она у меня не подключена. Ок, жду ответа.

**Comment by pagapitov** [comment]
@PavlikBender на i7 3770 есть avx и обе версии запускаются и работают на win 10

**Comment by PavlikBender** [comment]
@pagapitov Понял значит проблема в AVX. Обновил readme. Закрываю этот issue
